services:
  - type: web
    name: gf-bf
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: AGORA_APP_ID
        sync: false
      - key: AGORA_APP_CERTIFICATE
        sync: false
      - key: ADMIN_EMAIL
        sync: false
